####################################################################################################
#                                            tapo-p110m
# DEVICES:
#     User button on the side
#     Blue LED
#     Orange Status LED
#     Relay to control mains power outlet
#     BL0937 Energy monitoring chip - NOT FUNCTIONAL WITH CURRENT CODE
####################################################################################################
substitutions:
  device_name: "tapo-p110m"
  friendly_name: "Tapo P110M"
  modelnum: "Tapo P110M"
  user_button: "P17"
  relay_pin: "P14"
  blue_led: "P18"
  orange_led: "P19"
  sel_pin: "P2"
  cf_pin: "P3"
  cf1_pin: "P4"

####################################################################################################
####################################################################################################
#                                             PACKAGES
####################################################################################################
####################################################################################################
packages:
  sensors: !include packages/.base_sensors.yaml

####################################################################################################
####################################################################################################
#                               BASIC/STANDARD CONFIG ENTRIES (SPECIALIZED)
####################################################################################################
####################################################################################################
rtl87xx:
  board: bw15
  #Uncomment for OTA updates
  framework:
    version: 0.0.0
    source: https://github.com/prokoma/libretiny.git#ambz2-ota

esphome:
  name: ${device_name}
  platformio_options:
    # board_upload.flash_size: 4194304
    # board_upload.maximum_size: 2031616
    # board_flash.ota1: "0x00C000+0x1F8000"
    # board_flash.ota2: "0x204000+0x1F8000"
    # board_flash.kvs: "0x3FC000+0x4000"
    extra_scripts: 
      - /home/michael/ESPHome/OpenBeken/fix_ota.py

wifi:
  use_address: "dining-rm-sw"
  # use_address: "192.168.2.244"
  networks: 
    - ssid: !secret ssid_home1
      password: !secret password_home1
    - ssid: !secret ssid_mega
      password: !secret password_mega
    - ssid: !secret ssid_nana
      password: !secret password_nana
  
  ap:
    password: !secret password_mega

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password
  platform: esphome

web_server:
  port: 80

captive_portal:

logger:
#  logs:  

####################################################################################################
####################################################################################################
#                                           BINARY SENSORS                                          
####################################################################################################
####################################################################################################
binary_sensor:
  # Main button
  - platform: gpio
    name: ${friendly_name} Button
    pin:
      number: ${user_button}
    id: user_button
    on_press:
      - switch.toggle: relay

####################################################################################################
####################################################################################################
#                                               LIGHTS                                              
####################################################################################################
####################################################################################################
light:
  # Onboard Blue LED
  - platform: binary
    name: ${friendly_name} Blue LED
    id: onboard_blue_led
    output: onboard_white_blue_output

####################################################################################################
####################################################################################################
#                                               OUTPUTS                                              
####################################################################################################
####################################################################################################
output:
  # Pin for Onboard Blue LED
  - platform: gpio
    pin:
      number: ${blue_led}
      inverted: no
    id: onboard_white_blue_output

####################################################################################################
####################################################################################################
#                                             STATUS LEDS                                              
####################################################################################################
####################################################################################################
status_led:
  # Onboard Orange LED
  pin:
    number: ${orange_led}
    inverted: no


####################################################################################################
####################################################################################################
#                                              SWITCHES                                             
####################################################################################################
####################################################################################################
switch:
  - platform: gpio
    name: ${friendly_name} Relay
    pin: ${relay_pin}
    id: relay
    icon: mdi:power-socket-us
    restore_mode: ALWAYS_OFF # Default off after reboot
    on_turn_on:
      - light.turn_on: onboard_blue_led
    on_turn_off:
      - light.turn_off: onboard_blue_led











